# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design_SetSolver.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 422)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        MainWindow.setFont(font)
        MainWindow.setWindowFilePath("")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        def newGridBox(i, x, y) :
            self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
            self.graphicsView.setObjectName("graphicsView" + str(i))
            self.graphicsView.setAutoFillBackground(True)
            self.gridLayout.addWidget(self.graphicsView, y, x, 1, 1)

        # Create gridBoxes
        i = 0
        for y in range (0,4) :
            if y > 0 :
                y = y + 1

            for x in range(0,3) :
                newGridBox(i, x, y)
                i = i + 1

#### RIGHT SIDE BEGINS HERE.

        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(450, 10, 341, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")

        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.frame_4 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        self.frame_4.setObjectName("frame_4")

        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 161, 51))

        font = QtGui.QFont()
        font.setFamily("Small Fonts")

        self.frame_5.setFont(font)
        self.frame_5.setObjectName("frame_5")



        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 163, 26))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelShape = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelShape.setObjectName("labelShape")
        self.labelShape.setText("Shape:")
        self.horizontalLayout_3.addWidget(self.labelShape)

        self.radioButtonWave = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButtonWave.setChecked(True)
        self.radioButtonWave.setAutoExclusive(True)
        self.radioButtonWave.setObjectName("radioButtonWave")
        self.radioButtonWave.setText("Wave")
        self.horizontalLayout_3.addWidget(self.radioButtonWave)

        self.radioButtonOval = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButtonOval.setAutoExclusive(True)
        self.radioButtonOval.setObjectName("radioButtonOval")
        self.radioButtonOval.setText("Oval")
        self.horizontalLayout_3.addWidget(self.radioButtonOval)

        self.radioButtonDiamond = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButtonDiamond.setAutoExclusive(True)
        self.radioButtonDiamond.setObjectName("radioButtonDiamond")
        self.radioButtonDiamond.setText("Diamond")
        self.horizontalLayout_3.addWidget(self.radioButtonDiamond)

        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        self.frame_3.setFont(font)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(0, 40, 35, 10))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 160, 26))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelColor = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelColor.setObjectName("labelColor")
        self.labelColor.setText("Color:")
        self.horizontalLayout_2.addWidget(self.labelColor)

        self.radioButtonRed = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButtonRed.setChecked(True)
        self.radioButtonRed.setAutoExclusive(True)
        self.radioButtonRed.setObjectName("radioButtonRed")
        self.radioButtonRed.setText("Red")
        self.horizontalLayout_2.addWidget(self.radioButtonRed)

        self.radioButtonGreen = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButtonGreen.setAutoExclusive(True)
        self.radioButtonGreen.setObjectName("radioButtonGreen")
        self.radioButtonGreen.setText("Green")
        self.horizontalLayout_2.addWidget(self.radioButtonGreen)

        self.radioButtonPurple = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButtonPurple.setAutoExclusive(True)
        self.radioButtonPurple.setObjectName("radioButtonPurple")
        self.radioButtonPurple.setText("Purple")
        self.horizontalLayout_2.addWidget(self.radioButtonPurple)


        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        self.frame_6.setFont(font)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayoutWidget_Color = QtWidgets.QWidget(self.frame_6)
        self.horizontalLayoutWidget_Color.setGeometry(QtCore.QRect(0, 0, 161, 26))
        self.horizontalLayoutWidget_Color.setObjectName("horizontalLayoutWidget_Color")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_Color)
        self.horizontalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelAmount = QtWidgets.QLabel(self.horizontalLayoutWidget_Color)
        self.labelAmount.setObjectName("labelAmount")
        self.labelAmount.setText("Amount:")
        self.horizontalLayout_4.addWidget(self.labelAmount)

        self.radioButtonColor1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_Color)
        self.radioButtonColor1.setChecked(True)
        self.radioButtonColor1.setAutoExclusive(True)
        self.radioButtonColor1.setObjectName("radioButtonColor1")
        self.radioButtonColor1.setText("1")
        self.horizontalLayout_4.addWidget(self.radioButtonColor1)

        self.radioButtonColor2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_Color)
        self.radioButtonColor2.setAutoExclusive(True)
        self.radioButtonColor2.setObjectName("radioButtonColor2")
        self.radioButtonColor2.setText("2")
        self.horizontalLayout_4.addWidget(self.radioButtonColor2)

        self.radioButtonColor3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_Color)
        self.radioButtonColor3.setAutoExclusive(True)
        self.radioButtonColor3.setObjectName("radioButtonColor3")
        self.radioButtonColor3.setText("3")
        self.horizontalLayout_4.addWidget(self.radioButtonColor3)


        self.gridLayout_4.addWidget(self.frame_6, 2, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        self.frame_7.setFont(font)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_7)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 179, 26))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelFilling = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.labelFilling.setObjectName("labelFilling")
        self.labelFilling.setText("Filling:")
        self.horizontalLayout_5.addWidget(self.labelFilling)

        self.radioButtonFull = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButtonFull.setChecked(True)
        self.radioButtonFull.setAutoExclusive(True)
        self.radioButtonFull.setObjectName("radioButtonFull")
        self.radioButtonFull.setText("Full")
        self.horizontalLayout_5.addWidget(self.radioButtonFull)

        self.radioButtonHalf = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButtonHalf.setAutoExclusive(True)
        self.radioButtonHalf.setObjectName("radioButtonHalf")
        self.radioButtonHalf.setText("Half")
        self.horizontalLayout_5.addWidget(self.radioButtonHalf)

        self.radioButtonEmpty = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButtonEmpty.setAutoExclusive(True)
        self.radioButtonEmpty.setObjectName("radioButtonEmpty")
        self.radioButtonEmpty.setText("Empty")
        self.horizontalLayout_5.addWidget(self.radioButtonEmpty)

        self.gridLayout_4.addWidget(self.frame_7, 3, 0, 1, 1)
        self.NewCard = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.NewCard.setObjectName("NewCard")
        self.NewCard.setText("Image of user generated card")
        self.gridLayout_4.addWidget(self.NewCard, 0, 1, 3, 1)
        self.AddCardButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.AddCardButton.setObjectName("AddCardButton")
        self.AddCardButton.setText("Add Card")

        self.gridLayout_4.addWidget(self.AddCardButton, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
